// Code generated by go-swagger; DO NOT EDIT.

// Package handler GO-12 01: Синхронное взаимодействие через REST
//
//	Schemes:
//	  http
//	Host: pdf-compose-service
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - multipart/form-data
//
//	Produces:
//	  - application/pdf
//
// swagger:meta
package handler
