// Code generated by go-swagger; DO NOT EDIT.

package handler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "GO-12 01: Синхронное взаимодействие через REST",
    "version": "1.0.0"
  },
  "host": "pdf-compose-service",
  "paths": {
    "/send": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/pdf"
        ],
        "summary": "Send file to pdf compose",
        "parameters": [
          {
            "type": "file",
            "name": "upfile1",
            "in": "formData",
            "required": true
          },
          {
            "type": "file",
            "name": "upfile2",
            "in": "formData"
          },
          {
            "type": "file",
            "name": "upfile3",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "A PDF file.",
            "schema": {
              "type": "file"
            }
          },
          "400": {
            "description": "Bad request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "GO-12 01: Синхронное взаимодействие через REST",
    "version": "1.0.0"
  },
  "host": "pdf-compose-service",
  "paths": {
    "/send": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/pdf"
        ],
        "summary": "Send file to pdf compose",
        "parameters": [
          {
            "type": "file",
            "name": "upfile1",
            "in": "formData",
            "required": true
          },
          {
            "type": "file",
            "name": "upfile2",
            "in": "formData"
          },
          {
            "type": "file",
            "name": "upfile3",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "A PDF file.",
            "schema": {
              "type": "file"
            }
          },
          "400": {
            "description": "Bad request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  }
}`))
}
