// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"mime/multipart"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// PostSendMaxParseMemory sets the maximum size in bytes for
// the multipart form parser for this operation.
//
// The default value is 32 MB.
// The multipart parser stores up to this + 10MB.
var PostSendMaxParseMemory int64 = 32 << 20

// NewPostSendParams creates a new PostSendParams object
//
// There are no default values defined in the spec.
func NewPostSendParams() PostSendParams {

	return PostSendParams{}
}

// PostSendParams contains all the bound params for the post send operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostSend
type PostSendParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: formData
	*/
	Upfile1 io.ReadCloser
	/*
	  In: formData
	*/
	Upfile2 io.ReadCloser
	/*
	  In: formData
	*/
	Upfile3 io.ReadCloser
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostSendParams() beforehand.
func (o *PostSendParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(PostSendMaxParseMemory); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}

	upfile1, upfile1Header, err := r.FormFile("upfile1")
	if err != nil {
		res = append(res, errors.New(400, "reading file %q failed: %v", "upfile1", err))
	} else if err := o.bindUpfile1(upfile1, upfile1Header); err != nil {
		// Required: true
		res = append(res, err)
	} else {
		o.Upfile1 = &runtime.File{Data: upfile1, Header: upfile1Header}
	}

	upfile2, upfile2Header, err := r.FormFile("upfile2")
	if err != nil && err != http.ErrMissingFile {
		res = append(res, errors.New(400, "reading file %q failed: %v", "upfile2", err))
	} else if err == http.ErrMissingFile {
		// no-op for missing but optional file parameter
	} else if err := o.bindUpfile2(upfile2, upfile2Header); err != nil {
		res = append(res, err)
	} else {
		o.Upfile2 = &runtime.File{Data: upfile2, Header: upfile2Header}
	}

	upfile3, upfile3Header, err := r.FormFile("upfile3")
	if err != nil && err != http.ErrMissingFile {
		res = append(res, errors.New(400, "reading file %q failed: %v", "upfile3", err))
	} else if err == http.ErrMissingFile {
		// no-op for missing but optional file parameter
	} else if err := o.bindUpfile3(upfile3, upfile3Header); err != nil {
		res = append(res, err)
	} else {
		o.Upfile3 = &runtime.File{Data: upfile3, Header: upfile3Header}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindUpfile1 binds file parameter Upfile1.
//
// The only supported validations on files are MinLength and MaxLength
func (o *PostSendParams) bindUpfile1(file multipart.File, header *multipart.FileHeader) error {
	return nil
}

// bindUpfile2 binds file parameter Upfile2.
//
// The only supported validations on files are MinLength and MaxLength
func (o *PostSendParams) bindUpfile2(file multipart.File, header *multipart.FileHeader) error {
	return nil
}

// bindUpfile3 binds file parameter Upfile3.
//
// The only supported validations on files are MinLength and MaxLength
func (o *PostSendParams) bindUpfile3(file multipart.File, header *multipart.FileHeader) error {
	return nil
}
